PROJECT_NAME_EXISTS = 'Проект с таким именем уже существует!'
PROJECT_NOT_EXISTS = 'Проект не найден!'
PROJECT_HAS_INVEST = 'В проект уже инвестированы средства!'
PROJECT_IS_CLOSED = 'Закрытый проект нельзя редактировать!'
FULL_AMOUNT_ERROR = 'Нельзя установить требуемую сумму меньше уже вложенной.'
USER_DELETING_PROHIBITED = 'Удаление пользователей запрещено!'