"""Second migration

Revision ID: af5b8def5d0a
Revises: 92e590ed4613
Create Date: 2022-06-01 20:01:18.602868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5b8def5d0a'
down_revision = '92e590ed4613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
